### ISSUE TITLE
Example for adding custom commands is needed

### ISSUE THREAD

**Issue by tim-yao** [nightwatchjs-community/nightwatch-typescript-boilerplate#5]
I need an example for adding custom commands in a TypeScript way. 
It's missing.
Thanks.

**Comment by swrdfish** [comment]
@tim-yao can you take look at the following https://github.com/nightwatchjs/nightwatch/issues/3541#issuecomment-1372570435 and see if this helps?

**Comment by tim-yao** [comment]
> @tim-yao can you take look at the following [nightwatchjs/nightwatch#3541 (comment)](https://github.com/nightwatchjs/nightwatch/issues/3541#issuecomment-1372570435) and see if this helps?

Thanks @swrdfish 
I just did a quick test, seems to be working... will do more practice soon and let you know how it goes!
